services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=../db_password.txt
      - MYSQL_ROOT_HOST='127.0.0.1'
      - MYSQL_USER=Nadim
      - MYSQL_PASSWORD=../db_password.txt
      - MYSQL_DATABASE=papl
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  web:
    build: .
    env_file:
      - path: ../papl.env
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    links: 
      - db:db

