services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: Nadim
      MYSQL_PASSWORD: ../db_password.txt
      MYSQL_DATABASE: papl
    ports:
      - "3306:3306"
    volumes:
      - db-papl:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  web:
    build: .
    env_file:
      - path: ../papl.env
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    links: 
      - db:db
volumes:
  db-papl: