[tool.pytest.ini_options]
pythonpath = [
  "."
]
asyncio_mode="auto"
env_files = ".env"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
profile = "black"